#!/usr/bin/env bash
set -eu
gem5_build_dir="${1:-../gem5}"
if [ $# -gt 1 ]; then
  gem5_src_dir="$2"
else
  gem5_src_dir="$gem5_build_dir"
fi
"${gem5_build_dir}/build/ARM/gem5.opt" \
  --debug-file=trace.txt \
  --debug-flags='Exec' \
  "${gem5_src_dir}/configs/example/fs.py" \
  --bare-metal \
  --disk-image="$(pwd)/../fake.iso" \
  --kernel="$(pwd)/main.elf" \
  --machine-type=RealView_PBX \
  --mem-size=256MB \
;
